# -*- coding: utf-8 -*-
"""Tetris_test_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc5qxyieBA4JAkZBLDtXrO8FfgLWmwWk
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !git clone https://github.com/DuyMinhLe13/Double-Agent-Tetris
# !pip install pygame
# !git clone https://github.com/DuyMinhLe13/notebook-video-writer
# import os
# import shutil
# shutil.move('/content/Double-Agent-Tetris/TetrisBattle', '/content')
# shutil.move('/content/Double-Agent-Tetris/CustomAgent.py', '/content')
# shutil.move('notebook-video-writer/notebook_video_writer', '/content')

# Nếu bạn muốn chắc chắn xóa từ thư mục gốc Colab, thêm đường dẫn
!rm -rf /content/*

"""# Nộp hai file agent1.zip và agent2.zip"""

############## Chạy dòng này để xóa file agent1 và agent2 cũ để nộp hai file mới ###########

import os
import shutil

# Đường dẫn đến các file ZIP và thư mục đã giải nén
file_zip1 = "/content/agent1.zip"
file_zip2 = "/content/agent2.zip"
output_dir1 = "/content/agent1"
output_dir2 = "/content/agent2"

# Hàm xóa file hoặc thư mục
def delete_path(path):
    if os.path.exists(path):
        if os.path.isfile(path):
            os.remove(path)  # Xóa file
            print(f"Đã xóa file: {path}")
        elif os.path.isdir(path):
            shutil.rmtree(path)  # Xóa thư mục và tất cả nội dung bên trong
            print(f"Đã xóa thư mục: {path}")
    else:
        print(f"Đường dẫn không tồn tại: {path}")

# Xóa file ZIP và thư mục giải nén
delete_path(file_zip1)
delete_path(file_zip2)
delete_path(output_dir1)
delete_path(output_dir2)

print("Đã xóa toàn bộ file ZIP và các thư mục giải nén.")

from TetrisBattle.envs.tetris_env import TetrisDoubleEnv, TetrisSingleEnv
from notebook_video_writer import VideoWriter

import sys
from zipfile import ZipFile
from zipfile import ZipFile

# Đường dẫn đến các file ZIP
file_zip1 = "/content/agent1.zip"
file_zip2 = "/content/agent2.zip"

# Thư mục để giải nén
output_dir1 = "/content/"
output_dir2 = "/content/"

# Giải nén file ZIP 1
with ZipFile(file_zip1, 'r') as zip_ref:
    zip_ref.extractall(output_dir1)

# Giải nén file ZIP 2
with ZipFile(file_zip2, 'r') as zip_ref:
    zip_ref.extractall(output_dir2)

print("Cả hai file ZIP đã được giải nén.")

import sys

# Thêm thư mục vào sys.path
sys.path.append("/content/")

# Import các class từ các file
from agent1.Agent import Agent as Agent1  # Từ agent1.zip
from agent2.Agent import Agent as Agent2  # Từ agent2.zip

print("Đã import thành công hai class Agent từ các file khác nhau.")

env = TetrisDoubleEnv()
done = False
state = env.reset()
agent_list = [Agent1(0), Agent2(1)]

with VideoWriter(fps=50) as vw:
  while not done:
      vw.add(env.render(mode='rgb_array'))
      action = agent_list[env.game_interface.getCurrentPlayerID()].choose_action(state)
      state, reward, done, _ = env.step(action)
      env.take_turns()

  vw.add(env.render(mode='rgb_array'))

"""# Nộp 1 file agent.zip"""

############## Chạy dòng này để xóa file agemt cũ để nộp file mới ###########

import os
import shutil

# Đường dẫn đến các file ZIP và thư mục đã giải nén
file_zip = "/content/agent.zip"
output_dir = "/content/agent"


# Hàm xóa file hoặc thư mục
def delete_path(path):
    if os.path.exists(path):
        if os.path.isfile(path):
            os.remove(path)  # Xóa file
            print(f"Đã xóa file: {path}")
        elif os.path.isdir(path):
            shutil.rmtree(path)  # Xóa thư mục và tất cả nội dung bên trong
            print(f"Đã xóa thư mục: {path}")
    else:
        print(f"Đường dẫn không tồn tại: {path}")

# Xóa file ZIP và thư mục giải nén
delete_path(file_zip)
delete_path(output_dir)

print("Đã xóa toàn bộ file ZIP và các thư mục giải nén.")

from TetrisBattle.envs.tetris_env import TetrisDoubleEnv, TetrisSingleEnv
from notebook_video_writer import VideoWriter

import sys
from zipfile import ZipFile
from zipfile import ZipFile

# Đường dẫn đến các file ZIP
file_zip = "/content/agent.zip"

# Thư mục để giải nén
output_dir = "/content/"

# Giải nén file ZIP
with ZipFile(file_zip, 'r') as zip_ref:
    zip_ref.extractall(output_dir)

print("File ZIP đã được giải nén.")

import sys
# Thêm thư mục vào sys.path
sys.path.append("/content/")

# Import các class từ các file
from agent.Agent import Agent  # Từ agent.zip

print("Đã import thành công.")

env = TetrisSingleEnv()
done = False
state = env.reset()
agent = Agent(0)
with VideoWriter(fps=50) as vw:
  while not done:
      vw.add(env.render(mode='rgb_array'))
      action = agent.choose_action(state)
      state, reward, done, _ = env.step(action)

  vw.add(env.render(mode='rgb_array'))
